[new Model] VespaG
OATML-Markslab/ProteinGym pull request #30
Opened 2024-05-05 00:53 UTC by JSchlensok

We'd love to contribute [VespaG](https://github.com/jSchlensok/vespag) as a new baseline model for the `DMS substitutions` benchmark.
You can reproduce our results as follows:
- download pre-computed ESM2 embeddings from [Zenodo](https://zenodo.org/records/11085958/files/proteingym_217_esm2.h5?download=1)
- create & activate Conda environment from `proteingym/baselines/vespag/environment.yml`
- run `scripts/scoring_DMS_zero_shot/scoring_VespaG_substitutions.sh`

Pre-computed Spearman values are also available on [Zenodo](https://zenodo.org/records/11085958/files/proteingym_performance_vespag.csv?download=1), as are [raw predicted scores for all mutants](https://zenodo.org/records/11085958/files/vespag_proteingym_rawpreds_by_training_dataset.zip?download=1) (training dataset used for final method: Human).

VespaG achieves an average Spearman r of 0.483 overall and a weighted average of 0.459.

Let me know if anything is missing or unclear!

2024-09-27 21:02 UTC, aaronkollasch requested changes
Hi @JSchlensok,

Thanks for submitting VespaG to ProteinGym, nice work! Sorry for the delay in reviewing.

We have a few suggested comments and suggested changes to make before merging. Replication looks good so far on our end, but I still have some checks to do for that as well.

Cheers,
Aaron

2024-09-30 11:40 UTC, JSchlensok commented on proteingym/baselines/vespag/environment.yml
> +  - numpy
This has been resolved in https://github.com/JSchlensok/VespaG/commit/dc16036c59060815d77efcd6e5385ad0288da823, will pull later

2024-09-30 11:41 UTC, JSchlensok commented on proteingym/baselines/vespag/model_weights/state_dict_v1.pt
Yes, that is certainly possible.

2024-10-13 15:30 UTC, JSchlensok commented on proteingym/baselines/vespag/model_weights/state_dict_v1.pt
resolved it via Torch Hub from the upstream GitHub repo instead

2024-10-13 15:32 UTC, JSchlensok commented
Hi @aaronkollasch,
thanks for taking the time and don't worry about the delay.
Took me a bit to get back to you as well, sorry! All requested changes have been addressed now. Let me know if you need anything further!

Best,
Julius

2024-10-29 19:58 UTC, aaronkollasch approved these changes

2024-10-31 02:44 UTC, pascalnotin commented
Thank you for the PR @JSchlensok, and for the review @aaronkollasch -- merging to main!

2024-10-31 02:44 UTC, merged